import sys
import os
import sqlite3

if sys.stdout.encoding != 'utf-8':
    try:
        sys.stdout.reconfigure(encoding='utf-8')
    except Exception:
        pass

from database import init_db, create_exam, exam_exists

COMPREHENSIVE_EXAMS = [
    # 1. CET EXAMS
    {
        'title': 'Rajasthan CET (Senior Secondary 12th Level) 2026 Notification',
        'slug': 'rajasthan-cet-12th-level-2026-notification',
        'category': 'State',
        'board_name': 'RSMSSB (Rajasthan Staff Selection Board, Jaipur)',
        'total_vacancies': 'Eligibility Test for Forester, Hostel Superintendent, Clerk, Constable, Jamadar',
        'short_description': 'Rajasthan Staff Selection Board (RSMSSB) has released notification for Rajasthan Common Eligibility Test (CET 12th Senior Secondary Level) 2026 for recruitment to various subordinate and ministerial services.',
        'status': 'Applications Open',
        'notification_date': 'May 2026',
        'apply_start_date': 'May 2026',
        'apply_last_date': 'June 2026 (11:59 PM)',
        'fee_last_date': 'June 2026',
        'correction_last_date': 'July 2026',
        'admit_card_date': 'October 2026',
        'exam_date': '23, 24, 25 & 26 October 2026',
        'result_date': 'December 2026',
        'fee_general': '₹600 (General / Creamy Layer OBC / EWS)',
        'fee_reserved': '₹400 (Non-Creamy OBC, EWS, SC, ST, PwD of Rajasthan)',
        'fee_payment_mode': 'Online One Time Registration (OTR) through SSO Rajasthan / E-Mitra',
        'min_age': '18 Years',
        'max_age': '40 Years',
        'age_as_on': '01-01-2027',
        'age_relaxation': 'Male SC/ST/OBC/EWS of Rajasthan: 5 Years | Female SC/ST/OBC/EWS: 10 Years',
        'eligibility_criteria': 'Passed Senior Secondary (10+2) Examination from recognized Board or equivalent qualification.',
        'selection_process': '1. Rajasthan CET 12th Level Written Exam (300 Marks)\n2. Score Card with 1-Year Validity\n3. Main exam / typing test for specific department vacancies according to CET score rank.',
        'syllabus_summary': 'Total 150 Questions, 300 Marks, 3 Hours. Subjects: History, Art, Culture, Literature, Tradition and Heritage of Rajasthan, Geography of Rajasthan & India, General Science, Reasoning & Mental Ability, General Hindi, General English, Basic Computer Knowledge, Current Affairs. No negative marking.',
        'how_to_apply': '1. Visit SSO Rajasthan portal: https://sso.rajasthan.gov.in/\n2. Login with SSO ID and open Recruitment Portal.\n3. Pay One Time Registration (OTR) fee if not already paid.\n4. Fill Rajasthan CET 12th Level Application Form and submit.',
        'link_apply_online': 'https://sso.rajasthan.gov.in/',
        'link_notification_pdf': 'https://rsmssb.rajasthan.gov.in/',
        'link_admit_card': 'https://rsmssb.rajasthan.gov.in/',
        'link_answer_key': 'https://rsmssb.rajasthan.gov.in/',
        'link_result': 'https://rsmssb.rajasthan.gov.in/',
        'link_official_website': 'https://rsmssb.rajasthan.gov.in/',
        'link_previous_papers': 'https://rsmssb.rajasthan.gov.in/',
        'meta_title': 'Rajasthan CET 12th Level 2026 Notification, Exam Date & Apply Online at rsmssb.rajasthan.gov.in',
        'meta_description': 'Check Rajasthan CET 12th Level 2026 Notification, eligibility criteria, exam date, syllabus, OTR fees and direct official SSO link to apply online at rsmssb.rajasthan.gov.in.',
        'keywords': 'Rajasthan CET 2026, CET 12th level 2026, rsmssb cet 2026, sso rajasthan cet, rajasthan cet syllabus, rsmssb rajasthan gov in, cet admit card, cet result',
        'is_featured': 1,
        'source_url': 'https://rsmssb.rajasthan.gov.in/cet-12th-2026'
    },
    {
        'title': 'Rajasthan CET (Graduation Level) 2026 Notification',
        'slug': 'rajasthan-cet-graduation-level-2026-notification',
        'category': 'State',
        'board_name': 'RSMSSB (Rajasthan Staff Selection Board, Jaipur)',
        'total_vacancies': 'Eligibility Test for Platoon Commander, Zilladar, Patwari, Junior Accountant, Tehsil Revenue Accountant, Supervisor',
        'short_description': 'Rajasthan Staff Selection Board (RSMSSB) invites online applications for Common Eligibility Test (CET Graduation Level) 2026 for recruitment to various graduate-level posts in Rajasthan state government departments.',
        'status': 'Applications Open',
        'notification_date': 'June 2026',
        'apply_start_date': 'June 2026',
        'apply_last_date': 'July 2026 (11:59 PM)',
        'fee_last_date': 'July 2026',
        'correction_last_date': 'August 2026',
        'admit_card_date': 'September 2026',
        'exam_date': '27 & 28 September 2026',
        'result_date': 'November 2026',
        'fee_general': '₹600 (General / Creamy Layer OBC)',
        'fee_reserved': '₹400 (Non-Creamy OBC, EWS, SC, ST, PwD of Rajasthan)',
        'fee_payment_mode': 'One Time Registration (OTR) online through SSO Rajasthan',
        'min_age': '18 to 21 Years (Post-wise)',
        'max_age': '40 Years',
        'age_as_on': '01-01-2027',
        'age_relaxation': 'SC/ST/OBC/EWS Male (Rajasthan): 5 Years | Female: 10 Years',
        'eligibility_criteria': 'Graduation degree in any stream from recognized University or equivalent qualification recognized by Government.',
        'selection_process': '1. CET Graduation Level Written Examination (300 Marks)\n2. Validity of CET Scorecard is 1 Year\n3. Department-wise Main Examinations / Interviews for 15 times candidates based on CET merit.',
        'syllabus_summary': '150 Questions, 300 Marks, 3 Hours. Subjects: History of India & Indian National Movement, History, Culture & Heritage of Rajasthan, Geography of India & Rajasthan, Indian Polity & Political System of Rajasthan, Economy of India & Rajasthan, Science & Tech, Reasoning, General Hindi, General English, Computer Knowledge, Current Events. No negative marking.',
        'how_to_apply': 'Apply through Rajasthan SSO portal: https://sso.rajasthan.gov.in/',
        'link_apply_online': 'https://sso.rajasthan.gov.in/',
        'link_notification_pdf': 'https://rsmssb.rajasthan.gov.in/',
        'link_admit_card': 'https://rsmssb.rajasthan.gov.in/',
        'link_answer_key': 'https://rsmssb.rajasthan.gov.in/',
        'link_result': 'https://rsmssb.rajasthan.gov.in/',
        'link_official_website': 'https://rsmssb.rajasthan.gov.in/',
        'link_previous_papers': 'https://rsmssb.rajasthan.gov.in/',
        'meta_title': 'Rajasthan CET Graduation Level 2026 Notification & Apply Online at rsmssb.rajasthan.gov.in',
        'meta_description': 'Rajasthan CET Graduation Level 2026 Notification details, eligibility criteria, exam date, syllabus, OTR fee and direct official SSO link to apply online.',
        'keywords': 'Rajasthan CET Graduation Level 2026, CET graduation 2026, rsmssb cet, sso login, rajasthan cet apply online, cet result, cet admit card',
        'is_featured': 1,
        'source_url': 'https://rsmssb.rajasthan.gov.in/cet-graduation-2026'
    },
    {
        'title': 'Haryana CET 2026 (Common Eligibility Test - Group C & D)',
        'slug': 'haryana-cet-2026-group-c-d-recruitment',
        'category': 'State',
        'board_name': 'HSSC (Haryana Staff Selection Commission, Panchkula)',
        'total_vacancies': 'Eligibility Test for 28,000+ Group C & D Vacancies',
        'short_description': 'Haryana Staff Selection Commission (HSSC) conducts the Common Eligibility Test (Haryana CET 2026) for recruitment to various Group C and Group D posts across Haryana state government departments.',
        'status': 'Applications Open',
        'notification_date': 'April 2026',
        'apply_start_date': 'April 2026',
        'apply_last_date': 'May 2026',
        'fee_last_date': 'May 2026',
        'correction_last_date': 'May 2026',
        'admit_card_date': 'July 2026',
        'exam_date': 'August 2026 (NTA CBT/OMR)',
        'result_date': 'October 2026',
        'fee_general': '₹500 (General / Non-Resident of Haryana)',
        'fee_reserved': '₹250 (SC / BC / EWS / Women of Haryana)',
        'fee_payment_mode': 'Online via One Time Registration (OTR) Portal',
        'min_age': '18 Years',
        'max_age': '42 Years',
        'age_as_on': 'Last date of application',
        'age_relaxation': 'SC/BC/EWS: 5 Years for Haryana residents',
        'eligibility_criteria': 'Group C: 12th Pass or Graduation with Hindi/Sanskrit up to Matric. Group D: 10th (Matriculation) Pass with Hindi/Sanskrit.',
        'selection_process': '1. Haryana CET Common Eligibility Test (95% Weightage)\n2. Socio-Economic Criteria & Experience (5% Weightage)\n3. Post-wise Skill Test / Mains exam for Group C posts.',
        'syllabus_summary': '100 MCQs, 95 Marks, 105 Minutes. General Awareness, Reasoning, Maths, Science, English, Hindi, Computer Knowledge (75% weightage); History, Current Affairs, Literature, Geography, Civics, Environment, Culture of Haryana (25% weightage).',
        'how_to_apply': 'Apply on Haryana One Time Registration portal: https://onetimeregn.haryana.gov.in/ or https://hssc.gov.in/',
        'link_apply_online': 'https://onetimeregn.haryana.gov.in/',
        'link_notification_pdf': 'https://hssc.gov.in/',
        'link_admit_card': 'https://hssc.gov.in/',
        'link_answer_key': 'https://hssc.gov.in/',
        'link_result': 'https://hssc.gov.in/',
        'link_official_website': 'https://hssc.gov.in/',
        'link_previous_papers': 'https://hssc.gov.in/',
        'meta_title': 'Haryana CET 2026 Notification, Group C & D Exam Date & Apply Online at hssc.gov.in',
        'meta_description': 'Check Haryana CET 2026 Notification, Group C & Group D eligibility criteria, syllabus, exam date, OTR registration link and apply online at hssc.gov.in.',
        'keywords': 'Haryana CET 2026, HSSC CET 2026, haryana cet group c, haryana cet group d, hssc gov in, onetimeregn haryana gov in, cet syllabus haryana, cet admit card',
        'is_featured': 1,
        'source_url': 'https://hssc.gov.in/cet-2026'
    },
    {
        'title': 'UPSSSC PET 2026 Notification (Preliminary Eligibility Test)',
        'slug': 'upsssc-pet-2026-notification-preliminary-eligibility-test',
        'category': 'State',
        'board_name': 'UPSSSC (Uttar Pradesh Subordinate Services Selection Commission)',
        'total_vacancies': 'State Eligibility Test for Group B & C Vacancies (Lekhpal, VDO, Junior Assistant)',
        'short_description': 'Uttar Pradesh Subordinate Services Selection Commission (UPSSSC) conducts the Preliminary Eligibility Test (PET 2026) for qualifying candidates for all Group C vacancies in Uttar Pradesh government.',
        'status': 'Applications Open',
        'notification_date': 'May 2026',
        'apply_start_date': 'May 2026',
        'apply_last_date': 'June 2026',
        'fee_last_date': 'June 2026',
        'correction_last_date': 'July 2026',
        'admit_card_date': 'October 2026',
        'exam_date': '28 & 29 October 2026 (Offline OMR)',
        'result_date': 'December 2026',
        'fee_general': '₹185 (General / OBC)',
        'fee_reserved': '₹95 (SC / ST) | ₹25 (PwD)',
        'fee_payment_mode': 'State Bank Collect / Online Net Banking / Debit Card / UPI',
        'min_age': '18 Years',
        'max_age': '40 Years',
        'age_as_on': '01-07-2026',
        'age_relaxation': 'OBC / SC / ST of UP: 5 Years',
        'eligibility_criteria': 'Candidate must have passed High School (10th) or equivalent examination from a recognized Board.',
        'selection_process': '1. UPSSSC PET Written Exam (100 Marks)\n2. PET Scorecard valid for 1 Year from result date\n3. Eligible to apply for UP Lekhpal, VDO, Junior Assistant, Cane Supervisor mains exams.',
        'syllabus_summary': '100 Questions, 100 Marks, 2 Hours. Subjects: Indian History (5), Indian National Movement (5), Geography (5), Indian Economy (5), Indian Constitution & Public Admin (5), General Science (5), Elementary Arithmetic (5), General Hindi (5), General English (5), Logic & Reasoning (5), Current Affairs (10), General Awareness (10), Hindi Unseen Passage (10), Graph Interpretation (10), Table Interpretation (10). Negative marking: 0.25 (1/4th).',
        'how_to_apply': 'Apply online on UPSSSC official portal: http://upsssc.gov.in/',
        'link_apply_online': 'http://upsssc.gov.in/',
        'link_notification_pdf': 'http://upsssc.gov.in/',
        'link_admit_card': 'http://upsssc.gov.in/',
        'link_answer_key': 'http://upsssc.gov.in/',
        'link_result': 'http://upsssc.gov.in/',
        'link_official_website': 'http://upsssc.gov.in/',
        'link_previous_papers': 'http://upsssc.gov.in/',
        'meta_title': 'UPSSSC PET 2026 Notification, Exam Date, Syllabus & Apply Online at upsssc.gov.in',
        'meta_description': 'UPSSSC PET 2026 Notification details, preliminary eligibility test application start date, last date, eligibility, syllabus, exam pattern, admit card and direct official link at upsssc.gov.in.',
        'keywords': 'UPSSSC PET 2026, upsssc pet notification, upsssc gov in, up pet exam date, pet syllabus 2026, pet admit card, up pet result',
        'is_featured': 1,
        'source_url': 'http://upsssc.gov.in/pet-2026'
    },
    {
        'title': 'NRA CET 2026 (National Recruitment Agency Common Eligibility Test)',
        'slug': 'nra-cet-2026-national-recruitment-agency-common-eligibility-test',
        'category': 'State',
        'board_name': 'NRA (National Recruitment Agency, Central Govt)',
        'total_vacancies': 'National Single Screening Test for SSC, Railway RRB & IBPS Banking',
        'short_description': 'National Recruitment Agency (NRA) is introducing the National Common Eligibility Test (NRA CET 2026) for non-gazetted Group B and C posts across SSC, RRB, and IBPS.',
        'status': 'Upcoming Notification',
        'notification_date': 'August 2026',
        'apply_start_date': 'August 2026',
        'apply_last_date': 'September 2026',
        'fee_last_date': 'September 2026',
        'correction_last_date': 'September 2026',
        'admit_card_date': 'November 2026',
        'exam_date': 'December 2026 (Computer Based Test)',
        'result_date': 'January 2027',
        'fee_general': '₹500 (General / OBC)',
        'fee_reserved': '₹250 (SC / ST / PwD / Female)',
        'fee_payment_mode': 'Online UPI / Cards / Net Banking',
        'min_age': '18 Years',
        'max_age': '30 Years',
        'age_as_on': '01-08-2026',
        'age_relaxation': 'OBC: 3 Years | SC/ST: 5 Years | PwD: 10 Years',
        'eligibility_criteria': 'Separate CET exams for Graduate Level, 12th Senior Secondary Level, and 10th Matriculation Level candidates.',
        'selection_process': '1. NRA CET Preliminary Computer Based Test (CBT)\n2. Scorecard valid for 3 Years\n3. Specialized Tier-II / Tier-III exams conducted by respective agencies (SSC, RRB, IBPS).',
        'syllabus_summary': 'Standardized computer-based objective test covering Quantitative Aptitude, General Intelligence & Reasoning, English / Hindi Language, and General Awareness in 12 Indian Languages.',
        'how_to_apply': 'Apply through official NRA portal once live: https://www.nra.nic.in/ or through ssc.gov.in, rrbapply.gov.in, ibps.in',
        'link_apply_online': 'https://ssc.gov.in/',
        'link_notification_pdf': 'https://www.nra.nic.in/',
        'link_admit_card': 'https://ssc.gov.in/',
        'link_answer_key': 'https://ssc.gov.in/',
        'link_result': 'https://ssc.gov.in/',
        'link_official_website': 'https://www.nra.nic.in/',
        'link_previous_papers': 'https://ssc.gov.in/',
        'meta_title': 'NRA CET 2026 Notification, Syllabus, Exam Date & Common Eligibility Test Details',
        'meta_description': 'Check NRA CET 2026 details, National Recruitment Agency common eligibility test syllabus, dates, pattern and direct official portal information.',
        'keywords': 'NRA CET 2026, national recruitment agency cet, common eligibility test 2026, nra cet syllabus, cet exam date, nra nic in',
        'is_featured': 0,
        'source_url': 'https://www.nra.nic.in/cet-2026'
    },

    # 2. POPULAR POLICE & DEFENSE EXAMS
    {
        'title': 'SSC GD Constable 2026 Notification (BSF, CISF, CRPF, SSB, ITBP, AR, SSF)',
        'slug': 'ssc-gd-constable-2026-notification-recruitment',
        'category': 'SSC',
        'board_name': 'Staff Selection Commission (SSC)',
        'total_vacancies': '39,481+ Posts',
        'short_description': 'Staff Selection Commission (SSC) has announced Constable (GD) in Central Armed Police Forces (CAPFs), SSF, and Rifleman (GD) in Assam Rifles Examination 2026.',
        'status': 'Applications Open',
        'notification_date': '05 September 2025',
        'apply_start_date': '05 September 2025',
        'apply_last_date': '14 October 2025 (11:00 PM)',
        'fee_last_date': '15 October 2025',
        'correction_last_date': '05 to 07 November 2025',
        'admit_card_date': 'January 2026',
        'exam_date': 'Computer Based Exam: Feb - March 2026',
        'result_date': 'May 2026',
        'fee_general': '₹100 (General / OBC / EWS Male)',
        'fee_reserved': '₹0 (Women, SC, ST, Ex-Servicemen)',
        'fee_payment_mode': 'Online BHIM UPI, Net Banking, Debit/Credit Card',
        'min_age': '18 Years',
        'max_age': '23 Years',
        'age_as_on': '01-01-2026',
        'age_relaxation': 'SC/ST: 5 Years | OBC: 3 Years | Ex-Servicemen: 3 Years',
        'eligibility_criteria': 'Candidate must have passed Matriculation (10th Class) Examination from a recognized Board/University.',
        'selection_process': '1. Computer Based Examination (CBE - 80 Qs - 160 Marks)\n2. Physical Efficiency Test (PET - 5km run in 24 mins for male)\n3. Physical Standard Test (PST - Height & Chest)\n4. Detailed Medical Examination (DME) & Document Verification.',
        'syllabus_summary': '80 MCQs, 160 Marks, 60 Minutes. General Intelligence & Reasoning (20 Qs - 40 M), General Knowledge & General Awareness (20 Qs - 40 M), Elementary Mathematics (20 Qs - 40 M), English/Hindi (20 Qs - 40 M). Negative marking: 0.25 marks per wrong answer.',
        'how_to_apply': 'Apply on official SSC portal: https://ssc.gov.in/',
        'link_apply_online': 'https://ssc.gov.in/',
        'link_notification_pdf': 'https://ssc.gov.in/',
        'link_admit_card': 'https://ssc.gov.in/',
        'link_answer_key': 'https://ssc.gov.in/',
        'link_result': 'https://ssc.gov.in/',
        'link_official_website': 'https://ssc.gov.in/',
        'link_previous_papers': 'https://ssc.gov.in/',
        'meta_title': 'SSC GD Constable 2026 Notification, Exam Date, Syllabus & Apply Online at ssc.gov.in',
        'meta_description': 'Check SSC GD Constable 2026 notification details, eligibility criteria, running test, syllabus, exam date, admit card and direct official link to apply online at ssc.gov.in.',
        'keywords': 'SSC GD 2026, ssc gd constable notification, ssc gd apply online, ssc gov in gd, ssc gd syllabus, ssc gd admit card, ssc gd result',
        'is_featured': 1,
        'source_url': 'https://ssc.gov.in/gd-constable-2026'
    },
    {
        'title': 'Rajasthan Police Constable Recruitment 2026',
        'slug': 'rajasthan-police-constable-recruitment-2026',
        'category': 'Police',
        'board_name': 'Rajasthan Police Department, Jaipur',
        'total_vacancies': '3,578+ Posts',
        'short_description': 'Rajasthan Police Department invites online applications for recruitment of Constable (General, Driver, Band, Mounted, Telecommunication) in Rajasthan Police.',
        'status': 'Applications Open',
        'notification_date': 'March 2026',
        'apply_start_date': 'March 2026',
        'apply_last_date': 'April 2026',
        'fee_last_date': 'April 2026',
        'correction_last_date': 'April 2026',
        'admit_card_date': 'June 2026',
        'exam_date': 'CBT Exam: June / July 2026',
        'result_date': 'August 2026',
        'fee_general': '₹600 (General / OBC / Other State)',
        'fee_reserved': '₹400 (SC / ST / EWS of Rajasthan)',
        'fee_payment_mode': 'Online through Rajasthan SSO portal',
        'min_age': '18 Years',
        'max_age': '24 Years (Relaxation for Driver/Special categories)',
        'age_as_on': '01-01-2027',
        'age_relaxation': 'SC/ST/OBC/MBC/EWS Male of Rajasthan: 5 Years | Female: 10 Years',
        'eligibility_criteria': 'Candidate must have qualified Rajasthan CET (12th Level) with minimum 40% (General/OBC/EWS) or 36% (SC/ST). Passed Senior Secondary (12th) from recognized Board. For Telecom: 12th with Physics and Maths.',
        'selection_process': '1. Physical Efficiency Test (PET - 5km running) & PST\n2. Computer Based Test (CBT - 150 Marks)\n3. Proficiency Test (for Drivers/Band/Mounted)\n4. Document Verification & Medical Exam.',
        'syllabus_summary': '150 Questions, 150 Marks, 2 Hours. Reasoning, Logic & Basic Computer (60 Qs - 60 Marks); General Knowledge, General Science, Social Science & Current Affairs + Women & Child Rights (45 Qs - 45 Marks); History, Geography, Economy, Art & Culture of Rajasthan (45 Qs - 45 Marks). Negative marking: 25% (0.25).',
        'how_to_apply': 'Apply online through SSO Rajasthan portal: https://sso.rajasthan.gov.in/ or https://police.rajasthan.gov.in/',
        'link_apply_online': 'https://sso.rajasthan.gov.in/',
        'link_notification_pdf': 'https://police.rajasthan.gov.in/',
        'link_admit_card': 'https://police.rajasthan.gov.in/',
        'link_answer_key': 'https://police.rajasthan.gov.in/',
        'link_result': 'https://police.rajasthan.gov.in/',
        'link_official_website': 'https://police.rajasthan.gov.in/',
        'link_previous_papers': 'https://police.rajasthan.gov.in/',
        'meta_title': 'Rajasthan Police Constable 2026 Notification, Exam Date & Apply Online at police.rajasthan.gov.in',
        'meta_description': 'Rajasthan Police Constable 2026 Notification details, CET cut-off eligibility, syllabus, physical criteria, running test, admit card and direct official link.',
        'keywords': 'Rajasthan Police Constable 2026, rajasthan police notification, police rajasthan gov in, rajasthan police cet cut off, sso rajasthan police, admit card police',
        'is_featured': 1,
        'source_url': 'https://police.rajasthan.gov.in/constable-2026'
    },
    {
        'title': 'Railway RPF Constable & Sub-Inspector (SI) 2026 Recruitment',
        'slug': 'railway-rpf-constable-si-2026-recruitment',
        'category': 'Railway',
        'board_name': 'Ministry of Railways (RRB / RPF)',
        'total_vacancies': '4,660+ Posts (4,208 Constable + 452 Sub-Inspector)',
        'short_description': 'Railway Recruitment Boards (RRBs) in coordination with Railway Protection Force (RPF) and RPSF announce recruitment for Constable (Executive) and Sub-Inspector (Executive) posts.',
        'status': 'Applications Open',
        'notification_date': '15 April 2026',
        'apply_start_date': '15 April 2026',
        'apply_last_date': '14 May 2026 (11:59 PM)',
        'fee_last_date': '14 May 2026',
        'correction_last_date': '15 to 24 May 2026',
        'admit_card_date': 'September 2026',
        'exam_date': 'Computer Based Test (CBT): Oct - Nov 2026',
        'result_date': 'December 2026',
        'fee_general': '₹500 (₹400 refunded after appearing in CBT)',
        'fee_reserved': '₹250 (₹250 refunded after appearing in CBT)',
        'fee_payment_mode': 'Online Net Banking / Debit/Credit Cards / UPI',
        'min_age': 'Constable: 18 Years | SI: 20 Years',
        'max_age': 'Constable: 28 Years | SI: 28 Years (3 Years COVID age relaxation included)',
        'age_as_on': '01-07-2026',
        'age_relaxation': 'SC/ST: 5 Years | OBC: 3 Years',
        'eligibility_criteria': 'Constable: 10th Pass (Matriculation) from recognized Board. Sub-Inspector: Bachelor Degree (Graduation) in any discipline from recognized University.',
        'selection_process': '1. Computer Based Test (CBT - 120 Questions - 120 Marks)\n2. Physical Efficiency Test (PET) & Physical Measurement Test (PMT)\n3. Document Verification (DV) & Medical Examination.',
        'syllabus_summary': '120 Questions, 120 Marks, 90 Minutes. Basic Arithmetic (35 Qs), General Intelligence & Reasoning (35 Qs), General Awareness (50 Qs). Negative marking: 1/3rd (0.33) per incorrect response.',
        'how_to_apply': 'Apply through official RRB centralized application portal: https://www.rrbapply.gov.in/',
        'link_apply_online': 'https://www.rrbapply.gov.in/',
        'link_notification_pdf': 'https://www.rrbapply.gov.in/',
        'link_admit_card': 'https://www.rrbapply.gov.in/',
        'link_answer_key': 'https://www.rrbapply.gov.in/',
        'link_result': 'https://www.rrbapply.gov.in/',
        'link_official_website': 'https://www.rrbapply.gov.in/',
        'link_previous_papers': 'https://www.rrbapply.gov.in/',
        'meta_title': 'Railway RPF Constable & SI 2026 Notification, Exam Date & Apply Online at rrbapply.gov.in',
        'meta_description': 'Check Railway RPF Constable and Sub-Inspector 2026 notification details, CEN 01/2024 & CEN 02/2024, syllabus, physical standards, exam date and direct official link.',
        'keywords': 'RPF Constable 2026, RPF SI 2026, railway rpf recruitment, rrbapply gov in, rpf exam date, rpf syllabus, rpf admit card',
        'is_featured': 1,
        'source_url': 'https://www.rrbapply.gov.in/rpf-2026'
    },
    {
        'title': 'Railway RRB ALP (Assistant Loco Pilot) 2026 Recruitment',
        'slug': 'railway-rrb-alp-assistant-loco-pilot-2026-recruitment',
        'category': 'Railway',
        'board_name': 'Railway Recruitment Boards (RRB)',
        'total_vacancies': '18,799+ Posts',
        'short_description': 'Ministry of Railways has released Centralized Employment Notice for recruitment of Assistant Loco Pilot (ALP) across all Railway Recruitment Boards.',
        'status': 'Applications Open',
        'notification_date': 'January 2026',
        'apply_start_date': '20 January 2026',
        'apply_last_date': '19 February 2026',
        'fee_last_date': '19 February 2026',
        'correction_last_date': '20 to 29 February 2026',
        'admit_card_date': 'July 2026',
        'exam_date': 'CBT-1: August - September 2026 | CBT-2: November 2026',
        'result_date': 'October 2026',
        'fee_general': '₹500 (₹400 refunded upon appearing in CBT-1)',
        'fee_reserved': '₹250 (Full ₹250 refunded upon appearing in CBT-1)',
        'fee_payment_mode': 'Online UPI / Net Banking / Debit Card',
        'min_age': '18 Years',
        'max_age': '33 Years (Includes 3-year age relaxation)',
        'age_as_on': '01-07-2026',
        'age_relaxation': 'SC/ST: 5 Years | OBC: 3 Years',
        'eligibility_criteria': 'Matriculation / 10th Pass plus ITI from recognized NCVT/SCVT institutions in specified trades (Fitter, Electrician, Instrument Mechanic, Millwright, Wireman, Tractor Mechanic, etc.) OR 3 Years Diploma in Mechanical/Electrical/Electronics/Automobile Engineering OR B.E/B.Tech degree.',
        'selection_process': '1. First Stage CBT (CBT-1 - Screening)\n2. Second Stage CBT (CBT-2 - Part A & Part B Technical Trade)\n3. Computer Based Aptitude Test (CBAT - Psycho Test)\n4. Document Verification & Medical Fitness (A-1 standard mandatory).',
        'syllabus_summary': 'CBT-1: 75 Qs, 60 Minutes. Maths (20), Mental Ability (25), General Science (20), General Awareness (10). Negative marking: 1/3rd.',
        'how_to_apply': 'Apply on official RRB portal: https://www.rrbapply.gov.in/',
        'link_apply_online': 'https://www.rrbapply.gov.in/',
        'link_notification_pdf': 'https://www.rrbapply.gov.in/',
        'link_admit_card': 'https://www.rrbapply.gov.in/',
        'link_answer_key': 'https://www.rrbapply.gov.in/',
        'link_result': 'https://www.rrbapply.gov.in/',
        'link_official_website': 'https://www.rrbapply.gov.in/',
        'link_previous_papers': 'https://www.rrbapply.gov.in/',
        'meta_title': 'Railway RRB ALP 2026 Notification, Exam Date, CBT Syllabus & Apply Online at rrbapply.gov.in',
        'meta_description': 'Check Railway Assistant Loco Pilot (RRB ALP 2026) vacancy notification, ITI trades, CBT-1 & CBT-2 syllabus, admit card and direct official apply online link.',
        'keywords': 'RRB ALP 2026, assistant loco pilot recruitment, rrb apply gov in, alp syllabus, alp exam date, alp admit card, alp result',
        'is_featured': 1,
        'source_url': 'https://www.rrbapply.gov.in/alp-2026'
    },
    {
        'title': 'Railway RRB Technician (Grade-I & Grade-III) 2026 Recruitment',
        'slug': 'railway-rrb-technician-grade-1-3-2026-recruitment',
        'category': 'Railway',
        'board_name': 'Railway Recruitment Boards (RRB)',
        'total_vacancies': '14,298+ Posts',
        'short_description': 'Railway Recruitment Boards (RRBs) invite online applications for recruitment of Technician Grade I Signal and Technician Grade III in various technical categories across Indian Railways.',
        'status': 'Applications Open',
        'notification_date': 'March 2026',
        'apply_start_date': '09 March 2026',
        'apply_last_date': '08 April 2026',
        'fee_last_date': '08 April 2026',
        'correction_last_date': '09 to 18 April 2026',
        'admit_card_date': 'October 2026',
        'exam_date': 'CBT Exam: October - November 2026',
        'result_date': 'January 2027',
        'fee_general': '₹500 (₹400 refunded after CBT)',
        'fee_reserved': '₹250 (Full ₹250 refunded after CBT)',
        'fee_payment_mode': 'Online UPI / Cards / Internet Banking',
        'min_age': 'Grade I: 18-36 Years | Grade III: 18-33 Years',
        'max_age': '36 Years (Grade I) | 33 Years (Grade III)',
        'age_as_on': '01-07-2026',
        'age_relaxation': 'SC/ST: 5 Years | OBC: 3 Years',
        'eligibility_criteria': 'Technician Gr I Signal: Bachelor of Science in Physics/Electronics/CS/IT OR Diploma/B.Tech in Engineering. Technician Gr III: 10th Matric + ITI in relevant trade OR 10+2 with Physics and Mathematics (for Technicians S&T).',
        'selection_process': '1. Computer Based Test (CBT - Single stage)\n2. Document Verification (DV)\n3. Medical Examination.',
        'syllabus_summary': '100 Questions, 100 Marks, 90 Minutes. General Awareness, General Intelligence & Reasoning, Basic Science and Engineering, Mathematics. Negative marking: 1/3rd.',
        'how_to_apply': 'Apply on official Railway portal: https://www.rrbapply.gov.in/',
        'link_apply_online': 'https://www.rrbapply.gov.in/',
        'link_notification_pdf': 'https://www.rrbapply.gov.in/',
        'link_admit_card': 'https://www.rrbapply.gov.in/',
        'link_answer_key': 'https://www.rrbapply.gov.in/',
        'link_result': 'https://www.rrbapply.gov.in/',
        'link_official_website': 'https://www.rrbapply.gov.in/',
        'link_previous_papers': 'https://www.rrbapply.gov.in/',
        'meta_title': 'Railway RRB Technician 2026 Notification, Exam Date, Syllabus & Apply Online',
        'meta_description': 'Check Railway RRB Technician Grade 1 & Grade 3 2026 vacancy notification, eligibility, syllabus, admit card and direct official link at rrbapply.gov.in.',
        'keywords': 'RRB Technician 2026, railway technician notification, rrbapply gov in technician, technician grade 1 3, rrb admit card',
        'is_featured': 0,
        'source_url': 'https://www.rrbapply.gov.in/tech-2026'
    },
    {
        'title': 'Rajasthan Patwari Recruitment 2026 Notification',
        'slug': 'rajasthan-patwari-recruitment-2026-notification',
        'category': 'State',
        'board_name': 'RSMSSB (Rajasthan Staff Selection Board, Jaipur)',
        'total_vacancies': '2,998+ Posts',
        'short_description': 'Rajasthan Staff Selection Board (RSMSSB) invites applications for recruitment to the post of Patwari in the Revenue Department of Government of Rajasthan.',
        'status': 'Upcoming Notification',
        'notification_date': 'July 2026',
        'apply_start_date': 'July 2026',
        'apply_last_date': 'August 2026',
        'fee_last_date': 'August 2026',
        'correction_last_date': 'August 2026',
        'admit_card_date': 'November 2026',
        'exam_date': 'December 2026',
        'result_date': 'February 2027',
        'fee_general': '₹600 (General / OBC)',
        'fee_reserved': '₹400 (SC / ST / EWS of Rajasthan)',
        'fee_payment_mode': 'One Time Registration (OTR) through SSO Rajasthan',
        'min_age': '18 Years',
        'max_age': '40 Years',
        'age_as_on': '01-01-2027',
        'age_relaxation': 'SC/ST/OBC Male: 5 Years | Female: 10 Years',
        'eligibility_criteria': 'Graduation degree in any stream from recognized University AND Computer Qualification (RS-CIT or O Level or Degree/Diploma in CS/IT) AND valid Rajasthan CET (Graduation Level) score.',
        'selection_process': '1. Candidate selection on basis of Rajasthan CET (Graduation Level) merit\n2. Patwari Main Written Examination\n3. Document Verification and Revenue Training.',
        'syllabus_summary': '150 Questions, 300 Marks, 3 Hours. General Science, History, Polity & Geography of India; General Knowledge, Current Affairs (38 Qs); Geography, History, Culture & Polity of Rajasthan (30 Qs); General English & Hindi (22 Qs); Mental Ability & Reasoning, Basic Numerical Efficiency (45 Qs); Basic Computer (15 Qs). Negative marking: 1/3rd.',
        'how_to_apply': 'Apply through SSO Rajasthan Recruitment Portal: https://sso.rajasthan.gov.in/',
        'link_apply_online': 'https://sso.rajasthan.gov.in/',
        'link_notification_pdf': 'https://rsmssb.rajasthan.gov.in/',
        'link_admit_card': 'https://rsmssb.rajasthan.gov.in/',
        'link_answer_key': 'https://rsmssb.rajasthan.gov.in/',
        'link_result': 'https://rsmssb.rajasthan.gov.in/',
        'link_official_website': 'https://rsmssb.rajasthan.gov.in/',
        'link_previous_papers': 'https://rsmssb.rajasthan.gov.in/',
        'meta_title': 'Rajasthan Patwari 2026 Notification, CET Cut-off & Apply Online at rsmssb.rajasthan.gov.in',
        'meta_description': 'Check Rajasthan Patwari 2026 Notification, CET Graduation eligibility, syllabus, exam date, OTR fees and direct official SSO link to apply online.',
        'keywords': 'Rajasthan Patwari 2026, patwari vacancy rajasthan, rsmssb patwari notification, sso rajasthan patwari, patwari syllabus, patwari admit card',
        'is_featured': 1,
        'source_url': 'https://rsmssb.rajasthan.gov.in/patwari-2026'
    },
    {
        'title': 'Rajasthan 1st & 2nd Grade Teacher (RPSC) 2026 Recruitment',
        'slug': 'rajasthan-1st-2nd-grade-teacher-rpsc-2026-recruitment',
        'category': 'Teaching',
        'board_name': 'RPSC (Rajasthan Public Service Commission, Ajmer)',
        'total_vacancies': '11,400+ Posts (Senior Teacher & School Lecturer)',
        'short_description': 'Rajasthan Public Service Commission (RPSC) conducts competitive examination for recruitment of School Lecturers (1st Grade) and Senior Teachers (2nd Grade) for Secondary Education Department.',
        'status': 'Upcoming Notification',
        'notification_date': 'August 2026',
        'apply_start_date': 'August 2026',
        'apply_last_date': 'September 2026',
        'fee_last_date': 'September 2026',
        'correction_last_date': 'September 2026',
        'admit_card_date': 'December 2026',
        'exam_date': 'December 2026 / January 2027',
        'result_date': 'March 2027',
        'fee_general': '₹600 (General / Other State)',
        'fee_reserved': '₹400 (OBC / SC / ST / EWS of Rajasthan)',
        'fee_payment_mode': 'One Time Registration (OTR) online via SSO Rajasthan',
        'min_age': '18 to 21 Years',
        'max_age': '40 Years',
        'age_as_on': '01-01-2027',
        'age_relaxation': 'SC/ST/OBC/MBC/EWS Male (Rajasthan): 5 Years | Female: 10 Years',
        'eligibility_criteria': '1st Grade (School Lecturer): Post Graduate in relevant subject with B.Ed / Shiksha Shastri. 2nd Grade (Senior Teacher): Graduate with relevant optional subject with B.Ed / D.El.Ed recognized by NCTE.',
        'selection_process': '1. Competitive Written Examination (Paper-I General Awareness & Paper-II Subject Specific)\n2. Merit List declaration by RPSC\n3. Document Verification & Counseling.',
        'syllabus_summary': 'Paper-I: General Awareness and General Studies (75 Qs - 150 Marks - 1.5 Hours). Paper-II: Subject Knowledge of concerned subject (150 Qs - 300 Marks - 2.5 Hours). Negative marking: 1/3rd.',
        'how_to_apply': 'Apply on official RPSC / SSO portal: https://rpsc.rajasthan.gov.in/ or https://sso.rajasthan.gov.in/',
        'link_apply_online': 'https://sso.rajasthan.gov.in/',
        'link_notification_pdf': 'https://rpsc.rajasthan.gov.in/',
        'link_admit_card': 'https://rpsc.rajasthan.gov.in/',
        'link_answer_key': 'https://rpsc.rajasthan.gov.in/',
        'link_result': 'https://rpsc.rajasthan.gov.in/',
        'link_official_website': 'https://rpsc.rajasthan.gov.in/',
        'link_previous_papers': 'https://rpsc.rajasthan.gov.in/',
        'meta_title': 'RPSC 1st & 2nd Grade Teacher 2026 Notification, Syllabus & Apply Online',
        'meta_description': 'Check RPSC 1st Grade School Lecturer and 2nd Grade Senior Teacher 2026 vacancy notification, eligibility, syllabus, exam date and direct official SSO link.',
        'keywords': 'RPSC 1st grade teacher 2026, RPSC 2nd grade teacher 2026, rajasthan teacher vacancy, rpsc rajasthan gov in, sso rajasthan teacher, rpsc admit card',
        'is_featured': 0,
        'source_url': 'https://rpsc.rajasthan.gov.in/teacher-2026'
    },
    {
        'title': 'UP Police Constable 2026 Re-Exam & New Recruitment',
        'slug': 'up-police-constable-2026-recruitment',
        'category': 'Police',
        'board_name': 'UPPRPB (Uttar Pradesh Police Recruitment & Promotion Board, Lucknow)',
        'total_vacancies': '60,244+ Posts',
        'short_description': 'Uttar Pradesh Police Recruitment and Promotion Board (UPPRPB) conducts written examination and physical tests for recruitment of Constables in Civil Police.',
        'status': 'Applications Open',
        'notification_date': 'December 2025',
        'apply_start_date': '27 December 2025',
        'apply_last_date': '16 January 2026',
        'fee_last_date': '18 January 2026',
        'correction_last_date': '20 January 2026',
        'admit_card_date': 'August 2026',
        'exam_date': 'Written Exam: 23, 24, 25, 30 & 31 August 2026',
        'result_date': 'November 2026',
        'fee_general': '₹400 (All Categories)',
        'fee_reserved': '₹400',
        'fee_payment_mode': 'Online via SBI e-Pay / Credit Card / Debit Card / UPI',
        'min_age': '18 Years',
        'max_age': '25 Years (Male) | 28 Years (Female) with 3-year relaxation',
        'age_as_on': '01-07-2026',
        'age_relaxation': 'SC/ST/OBC of UP: 5 Years',
        'eligibility_criteria': '10+2 (Intermediate) passed from any recognized Board in India.',
        'selection_process': '1. Offline OMR Based Written Examination (300 Marks)\n2. Document Verification (DV) & Physical Standard Test (PST)\n3. Physical Efficiency Test (PET - 4.8 km run in 25 mins for male).\n4. Final Merit List.',
        'syllabus_summary': '150 Questions, 300 Marks, 2 Hours. General Knowledge (38 Qs), General Hindi (37 Qs), Numerical & Mental Ability (38 Qs), Mental Aptitude/IQ/Reasoning (37 Qs). Negative marking: 0.50 marks per wrong answer.',
        'how_to_apply': 'Apply on official UPPRPB portal: https://uppbpb.gov.in/',
        'link_apply_online': 'https://uppbpb.gov.in/',
        'link_notification_pdf': 'https://uppbpb.gov.in/',
        'link_admit_card': 'https://uppbpb.gov.in/',
        'link_answer_key': 'https://uppbpb.gov.in/',
        'link_result': 'https://uppbpb.gov.in/',
        'link_official_website': 'https://uppbpb.gov.in/',
        'link_previous_papers': 'https://uppbpb.gov.in/',
        'meta_title': 'UP Police Constable 2026 Notification, Exam Date, Admit Card & Result at uppbpb.gov.in',
        'meta_description': 'Check UP Police Constable 2026 notification details, 60,244 vacancies, re-exam dates, exam city slip, admit card and direct official link at uppbpb.gov.in.',
        'keywords': 'UP Police Constable 2026, uppbpb gov in, up police exam date, up police admit card, up police result, up police answer key',
        'is_featured': 1,
        'source_url': 'https://uppbpb.gov.in/constable-2026'
    },
    {
        'title': 'UPTET 2026 Notification (Uttar Pradesh Teacher Eligibility Test)',
        'slug': 'uptet-2026-notification-up-teacher-eligibility-test',
        'category': 'Teaching',
        'board_name': 'UP Education Service Commission (UPESC / UPDELED)',
        'total_vacancies': 'State Eligibility Test for Primary & Upper Primary Teachers',
        'short_description': 'Uttar Pradesh Education Service Selection Commission conducts UPTET 2026 for determining eligibility of teachers for Primary (Classes 1-5) and Upper Primary (Classes 6-8) schools in UP.',
        'status': 'Upcoming Notification',
        'notification_date': 'July 2026',
        'apply_start_date': 'July 2026',
        'apply_last_date': 'August 2026',
        'fee_last_date': 'August 2026',
        'correction_last_date': 'August 2026',
        'admit_card_date': 'October 2026',
        'exam_date': 'November 2026 (Paper 1 & Paper 2)',
        'result_date': 'January 2027',
        'fee_general': 'Single Paper: ₹600 | Both Papers: ₹1200',
        'fee_reserved': 'Single Paper: ₹400 (SC/ST) | ₹100 (PwD)',
        'fee_payment_mode': 'Online Net Banking / Debit Card / UPI via SBI Collect',
        'min_age': '18 Years',
        'max_age': 'No Upper Age Limit',
        'age_as_on': 'Notification date',
        'age_relaxation': 'As per NCTE guidelines',
        'eligibility_criteria': 'Paper I: 10+2 with D.El.Ed (BTC) / B.El.Ed. Paper II: Graduation with D.El.Ed / B.Ed / B.A.Ed / B.Sc.Ed.',
        'selection_process': '1. Offline OMR Written Examination\n2. Paper I (Primary Level) & Paper II (Upper Primary Level)\n3. Qualifying marks: 60% (90 marks) for General, 55% (82 marks) for Reserved categories. Lifetime validity.',
        'syllabus_summary': '150 MCQs, 150 Marks, 2.5 Hours. Child Development & Pedagogy (30), Language I Hindi (30), Language II English/Urdu/Sanskrit (30), Mathematics (30), Environmental Studies (30). No negative marking.',
        'how_to_apply': 'Apply on official UP DELED portal: https://updeled.gov.in/',
        'link_apply_online': 'https://updeled.gov.in/',
        'link_notification_pdf': 'https://updeled.gov.in/',
        'link_admit_card': 'https://updeled.gov.in/',
        'link_answer_key': 'https://updeled.gov.in/',
        'link_result': 'https://updeled.gov.in/',
        'link_official_website': 'https://updeled.gov.in/',
        'link_previous_papers': 'https://updeled.gov.in/',
        'meta_title': 'UPTET 2026 Notification, Exam Date, Syllabus & Apply Online at updeled.gov.in',
        'meta_description': 'Check UPTET 2026 Notification, eligibility criteria, exam date, Paper 1 and Paper 2 syllabus, admit card and direct official link at updeled.gov.in.',
        'keywords': 'UPTET 2026, uptet notification, updeled gov in, uptet exam date, uptet syllabus, uptet admit card, uptet result',
        'is_featured': 1,
        'source_url': 'https://updeled.gov.in/uptet-2026'
    },
    {
        'title': 'KVS Teacher (PRT, TGT, PGT) 2026 Recruitment',
        'slug': 'kvs-teacher-prt-tgt-pgt-2026-recruitment',
        'category': 'Teaching',
        'board_name': 'KVS (Kendriya Vidyalaya Sangathan, New Delhi)',
        'total_vacancies': '12,500+ Posts (PRT, TGT, PGT & Non-Teaching)',
        'short_description': 'Kendriya Vidyalaya Sangathan (KVS) invites online applications for recruitment of Primary Teachers (PRT), Trained Graduate Teachers (TGT), Post Graduate Teachers (PGT), and Non-Teaching staff across India.',
        'status': 'Upcoming Notification',
        'notification_date': 'September 2026',
        'apply_start_date': 'September 2026',
        'apply_last_date': 'October 2026',
        'fee_last_date': 'October 2026',
        'correction_last_date': 'October 2026',
        'admit_card_date': 'December 2026',
        'exam_date': 'CBT Exam: December 2026 / January 2027',
        'result_date': 'March 2027',
        'fee_general': 'PRT/TGT: ₹1500 | PGT: ₹1500',
        'fee_reserved': '₹0 (SC / ST / PwD / Ex-Servicemen)',
        'fee_payment_mode': 'Online Debit/Credit Card / Net Banking',
        'min_age': '18 Years',
        'max_age': 'PRT: 30 Years | TGT: 35 Years | PGT: 40 Years',
        'age_as_on': 'Last date of application',
        'age_relaxation': 'Women (all categories for teaching posts): 10 Years | SC/ST: 5 Years | OBC: 3 Years',
        'eligibility_criteria': 'PRT: 12th with 50% + D.El.Ed + CTET Paper-I qualified. TGT: Bachelor Degree with 50% in relevant subject + B.Ed + CTET Paper-II qualified. PGT: Master Degree with 50% in relevant subject + B.Ed.',
        'selection_process': '1. Computer Based Test (CBT - 180 Marks)\n2. Professional Competency Test (Demo Teaching - 30 Marks + Interview - 30 Marks)\n3. Merit weightage: 70% CBT + 30% Interview.',
        'syllabus_summary': '180 Questions, 180 Marks, 180 Minutes. General English (10), General Hindi (10), GK & Current Affairs (10), Reasoning Ability (5), Computer Literacy (5), Perspectives on Education and Leadership (40), Subject Specific Syllabus (100). No negative marking.',
        'how_to_apply': 'Apply on official KVS portal: https://kvsangathan.nic.in/',
        'link_apply_online': 'https://kvsangathan.nic.in/',
        'link_notification_pdf': 'https://kvsangathan.nic.in/',
        'link_admit_card': 'https://kvsangathan.nic.in/',
        'link_answer_key': 'https://kvsangathan.nic.in/',
        'link_result': 'https://kvsangathan.nic.in/',
        'link_official_website': 'https://kvsangathan.nic.in/',
        'link_previous_papers': 'https://kvsangathan.nic.in/',
        'meta_title': 'KVS Teacher Recruitment 2026 Notification, PRT TGT PGT Syllabus & Apply Online',
        'meta_description': 'Check KVS Teacher 2026 Notification, PRT, TGT, PGT eligibility criteria, CTET requirements, syllabus, exam date and direct official link at kvsangathan.nic.in.',
        'keywords': 'KVS recruitment 2026, kvs prt notification, kvs tgt pgt 2026, kvsangathan nic in, kvs syllabus, kvs admit card, kvs teacher result',
        'is_featured': 0,
        'source_url': 'https://kvsangathan.nic.in/recruitment-2026'
    },
    {
        'title': 'Rajasthan RAS / RTS Combined Competitive Exam 2026',
        'slug': 'rajasthan-ras-rts-exam-2026-notification',
        'category': 'State',
        'board_name': 'RPSC (Rajasthan Public Service Commission, Ajmer)',
        'total_vacancies': '905+ Posts (State Services & Subordinate Services)',
        'short_description': 'Rajasthan Public Service Commission (RPSC) conducts the Rajasthan State and Subordinate Services Combined Competitive Examination (RAS/RTS 2026).',
        'status': 'Applications Open',
        'notification_date': 'July 2026',
        'apply_start_date': 'July 2026',
        'apply_last_date': 'August 2026',
        'fee_last_date': 'August 2026',
        'correction_last_date': 'August 2026',
        'admit_card_date': 'September 2026',
        'exam_date': 'RAS Prelims: October 2026 | RAS Mains: Feb 2027',
        'result_date': 'November 2026',
        'fee_general': '₹600 (General / Creamy Layer OBC / Other State)',
        'fee_reserved': '₹400 (Non-Creamy OBC, EWS, SC, ST, PwD of Rajasthan)',
        'fee_payment_mode': 'One Time Registration (OTR) online via SSO Rajasthan',
        'min_age': '21 Years',
        'max_age': '40 Years',
        'age_as_on': '01-01-2027',
        'age_relaxation': 'SC/ST/OBC Male (Rajasthan): 5 Years | Female: 10 Years',
        'eligibility_criteria': 'Must hold a Degree of any of the Universities incorporated by an Act of the Central or State Legislature in India or other Educational Institution established by an Act of Parliament.',
        'selection_process': '1. Preliminary Examination (Objective - 200 Marks)\n2. Main Written Examination (Descriptive 4 Papers - 800 Marks)\n3. Personality & Viva-Voce Examination (Interview - 100 Marks).',
        'syllabus_summary': 'Prelims: General Knowledge & General Science (150 Qs - 200 Marks - 3 Hours). Covers History, Art, Culture, Literature, Tradition & Heritage of Rajasthan; Indian History; Geography of World, India & Rajasthan; Indian Constitution, Political System & Governance; Administrative System of Rajasthan; Economic Concepts & Indian Economy; Economy of Rajasthan; Science & Tech; Reasoning & Mental Ability; Current Affairs. Negative marking: 1/3rd.',
        'how_to_apply': 'Apply on official RPSC / SSO portal: https://rpsc.rajasthan.gov.in/ or https://sso.rajasthan.gov.in/',
        'link_apply_online': 'https://sso.rajasthan.gov.in/',
        'link_notification_pdf': 'https://rpsc.rajasthan.gov.in/',
        'link_admit_card': 'https://rpsc.rajasthan.gov.in/',
        'link_answer_key': 'https://rpsc.rajasthan.gov.in/',
        'link_result': 'https://rpsc.rajasthan.gov.in/',
        'link_official_website': 'https://rpsc.rajasthan.gov.in/',
        'link_previous_papers': 'https://rpsc.rajasthan.gov.in/',
        'meta_title': 'Rajasthan RAS 2026 Notification, Exam Date, Syllabus & Apply Online at rpsc.rajasthan.gov.in',
        'meta_description': 'Check RPSC RAS / RTS 2026 Notification, eligibility criteria, prelims exam date, syllabus, OTR fees and direct official SSO link to apply online.',
        'keywords': 'RAS 2026, RPSC RAS notification, ras exam date 2026, ras syllabus, rpsc rajasthan gov in, sso rajasthan ras, ras admit card, ras result',
        'is_featured': 1,
        'source_url': 'https://rpsc.rajasthan.gov.in/ras-2026'
    },
    {
        'title': 'SSC MTS & Havaldar 2026 Notification',
        'slug': 'ssc-mts-havaldar-2026-notification-recruitment',
        'category': 'SSC',
        'board_name': 'Staff Selection Commission (SSC)',
        'total_vacancies': '9,583+ Posts',
        'short_description': 'Staff Selection Commission (SSC) conducts Multi Tasking (Non-Technical) Staff and Havaldar (CBIC and CBN) Examination 2026.',
        'status': 'Applications Open',
        'notification_date': 'June 2026',
        'apply_start_date': 'June 2026',
        'apply_last_date': 'July 2026',
        'fee_last_date': 'July 2026',
        'correction_last_date': 'August 2026',
        'admit_card_date': 'September 2026',
        'exam_date': 'Computer Based Exam: October - November 2026',
        'result_date': 'December 2026',
        'fee_general': '₹100 (General / OBC Male)',
        'fee_reserved': '₹0 (Women, SC, ST, PwD, ESM)',
        'fee_payment_mode': 'Online UPI, Net Banking, Cards via ssc.gov.in',
        'min_age': '18 Years',
        'max_age': '25 Years (MTS) | 27 Years (Havaldar and few MTS posts)',
        'age_as_on': '01-08-2026',
        'age_relaxation': 'SC/ST: 5 Years | OBC: 3 Years | PwD: 10 Years',
        'eligibility_criteria': 'Candidate must have passed Matriculation (10th Class) Examination from a recognized Board.',
        'selection_process': '1. Computer Based Examination (Session-I & Session-II)\n2. Physical Efficiency Test (PET - 1600m walking in 15 mins for male Havaldar)\n3. Document Verification.',
        'syllabus_summary': 'Session-I: Numerical & Mathematical Ability (20 Qs - 60 Marks) + Reasoning Ability (20 Qs - 60 Marks) - 45 Mins, No negative marking. Session-II: General Awareness (25 Qs - 75 Marks) + English Language (25 Qs - 75 Marks) - 45 Mins, 1 mark negative per wrong answer.',
        'how_to_apply': 'Apply on official SSC portal: https://ssc.gov.in/',
        'link_apply_online': 'https://ssc.gov.in/',
        'link_notification_pdf': 'https://ssc.gov.in/',
        'link_admit_card': 'https://ssc.gov.in/',
        'link_answer_key': 'https://ssc.gov.in/',
        'link_result': 'https://ssc.gov.in/',
        'link_official_website': 'https://ssc.gov.in/',
        'link_previous_papers': 'https://ssc.gov.in/',
        'meta_title': 'SSC MTS & Havaldar 2026 Notification, Exam Date, Syllabus & Apply Online at ssc.gov.in',
        'meta_description': 'Check SSC MTS 2026 Notification, Havaldar vacancies, 10th pass eligibility, exam pattern, syllabus, admit card and direct official link at ssc.gov.in.',
        'keywords': 'SSC MTS 2026, ssc mts notification, ssc havaldar recruitment, ssc gov in mts, ssc mts syllabus, ssc mts admit card, ssc mts result',
        'is_featured': 1,
        'source_url': 'https://ssc.gov.in/mts-2026'
    },
    {
        'title': 'IBPS Clerk 2026 Notification (CRP Clerks-XIV)',
        'slug': 'ibps-clerk-2026-notification-recruitment',
        'category': 'Banking',
        'board_name': 'IBPS (Institute of Banking Personnel Selection)',
        'total_vacancies': '6,128+ Posts (Public Sector Banks)',
        'short_description': 'Institute of Banking Personnel Selection (IBPS) announces Common Recruitment Process (CRP Clerks-XIV) for clerical cadre posts in 11 participating Public Sector Banks.',
        'status': 'Applications Open',
        'notification_date': 'July 2026',
        'apply_start_date': 'July 2026',
        'apply_last_date': 'July 2026',
        'fee_last_date': 'July 2026',
        'correction_last_date': 'July 2026',
        'admit_card_date': 'August 2026',
        'exam_date': 'Prelims: August / September 2026 | Mains: October 2026',
        'result_date': 'November 2026',
        'fee_general': '₹850 (General / OBC / EWS)',
        'fee_reserved': '₹175 (SC / ST / PwBD / ESM)',
        'fee_payment_mode': 'Online Debit Card / Credit Card / Internet Banking / IMPS / Cash Card / Mobile Wallets',
        'min_age': '20 Years',
        'max_age': '28 Years',
        'age_as_on': '01-07-2026',
        'age_relaxation': 'SC/ST: 5 Years | OBC: 3 Years | PwD: 10 Years',
        'eligibility_criteria': 'A Degree (Graduation) in any discipline from a recognized University in India and Operating and working knowledge in computer systems.',
        'selection_process': '1. Preliminary Online Examination (100 Marks)\n2. Main Online Examination (200 Marks)\n3. Provisional Allotment in participating Banks based on Mains Score.',
        'syllabus_summary': 'Prelims: English Language (30 Qs), Numerical Ability (35 Qs), Reasoning Ability (35 Qs) - Total 100 Qs, 100 Marks, 60 Minutes (20 min sectional timing). Negative marking: 0.25 marks.',
        'how_to_apply': 'Apply on official IBPS portal: https://www.ibps.in/',
        'link_apply_online': 'https://www.ibps.in/',
        'link_notification_pdf': 'https://www.ibps.in/',
        'link_admit_card': 'https://www.ibps.in/',
        'link_answer_key': 'https://www.ibps.in/',
        'link_result': 'https://www.ibps.in/',
        'link_official_website': 'https://www.ibps.in/',
        'link_previous_papers': 'https://www.ibps.in/',
        'meta_title': 'IBPS Clerk 2026 Notification, Exam Date, Syllabus & Apply Online at ibps.in',
        'meta_description': 'Check IBPS Clerk 2026 Notification details, prelims and mains exam dates, eligibility, syllabus, admit card and direct official link at ibps.in.',
        'keywords': 'IBPS Clerk 2026, ibps clerk notification, ibps in clerk, bank clerk vacancy, ibps clerk syllabus, ibps clerk admit card, ibps clerk result',
        'is_featured': 0,
        'source_url': 'https://www.ibps.in/clerk-2026'
    },
    {
        'title': 'SBI PO (Probationary Officer) 2026 Notification',
        'slug': 'sbi-po-2026-notification-recruitment',
        'category': 'Banking',
        'board_name': 'State Bank of India (SBI)',
        'total_vacancies': '2,000+ Posts',
        'short_description': 'State Bank of India (SBI) invites online applications for recruitment of Probationary Officers (PO) across India with career growth opportunities and premier banking benefits.',
        'status': 'Upcoming Notification',
        'notification_date': 'September 2026',
        'apply_start_date': 'September 2026',
        'apply_last_date': 'October 2026',
        'fee_last_date': 'October 2026',
        'correction_last_date': 'October 2026',
        'admit_card_date': 'October 2026',
        'exam_date': 'Prelims: November 2026 | Mains: Dec 2026 / Jan 2027',
        'result_date': 'February 2027',
        'fee_general': '₹750 (General / EWS / OBC)',
        'fee_reserved': '₹0 (SC / ST / PwD)',
        'fee_payment_mode': 'Online Payment Gateway Debit / Credit Card / Internet Banking',
        'min_age': '21 Years',
        'max_age': '30 Years',
        'age_as_on': '01-04-2026',
        'age_relaxation': 'SC/ST: 5 Years | OBC: 3 Years | PwD: 10-15 Years',
        'eligibility_criteria': 'Graduation in any discipline from a recognized University or equivalent qualification recognized as such by the Central Government. Final year students may also apply provisionally.',
        'selection_process': '1. Phase-I: Preliminary Examination (100 Marks)\n2. Phase-II: Main Examination (Objective 200 Marks + Descriptive 50 Marks)\n3. Phase-III: Psychometric Test + Group Exercises (20 Marks) & Interview (30 Marks).',
        'syllabus_summary': 'Prelims: English Language (30), Quantitative Aptitude (35), Reasoning Ability (35) - 100 Marks, 1 Hour. Negative marking: 0.25.',
        'how_to_apply': 'Apply through official SBI Careers portal: https://bank.sbi/careers or https://www.sbi.co.in/careers',
        'link_apply_online': 'https://bank.sbi/careers',
        'link_notification_pdf': 'https://bank.sbi/careers',
        'link_admit_card': 'https://bank.sbi/careers',
        'link_answer_key': 'https://bank.sbi/careers',
        'link_result': 'https://bank.sbi/careers',
        'link_official_website': 'https://bank.sbi/careers',
        'link_previous_papers': 'https://bank.sbi/careers',
        'meta_title': 'SBI PO 2026 Notification, Exam Date, Syllabus & Apply Online at sbi.co.in/careers',
        'meta_description': 'Check SBI PO 2026 Notification details, probationary officer salary, eligibility, prelims and mains syllabus, admit card and direct official link.',
        'keywords': 'SBI PO 2026, sbi po notification, sbi co in careers, sbi probationary officer, sbi po syllabus, sbi po admit card, sbi po result',
        'is_featured': 1,
        'source_url': 'https://bank.sbi/careers/po-2026'
    }
]

def add_all_exams():
    init_db()
    added = 0
    skipped = 0
    for ex in COMPREHENSIVE_EXAMS:
        if exam_exists(ex['slug'], ex['title'], ex.get('source_url', '')):
            print(f"[SKIP - ALREADY EXISTS] {ex['title']}")
            skipped += 1
        else:
            create_exam(ex)
            print(f"[SUCCESS - ADDED] {ex['title']}")
            added += 1
    
    print(f"\nDone! Added: {added}, Skipped/Existing: {skipped}, Total Defined: {len(COMPREHENSIVE_EXAMS)}")

if __name__ == '__main__':
    add_all_exams()
